### ISSUE TITLE
Just trying to be nice

### ISSUE THREAD

**Issue by itayo** [ranareinsit/advent-of-code#1]
https://github.com/ranareinsit/advent-of-code/blob/20ca8b529b094b188512adeb70eff3684a9deb97/2024/src/lib/day_05/src/part_02.cpp#L56-L58

here you are using a 3 star swap algoritm to switch the data around. 
it might have been easier for u  to just do
Either
  copy[i] = prev;
  copy[i - 1] = curr;
  
  
  or if u change line 50/51 from
  https://github.com/ranareinsit/advent-of-code/blob/20ca8b529b094b188512adeb70eff3684a9deb97/2024/src/lib/day_05/src/part_02.cpp#L50-L51
  to
 auto &prev = copy[i - 1];
auto &curr = copy[i];

you can do a simplified std::swap(prev,curr)

Good luck with your stars :)
(i am looking at other peoples solutions to learn myself. Please see this as a tips more then a issue/complain)

**Comment by ranareinsit** [comment]
> 3 star swap algoritm
Oh yeah, damn elves awaken worst parts of me.
Still bad familiarized with std.

[Pushed](https://github.com/ranareinsit/advent-of-code/commit/5c77cb54f3d13f32811bed52531d20806220d33b) std::swap on today solution.
Merry Christmas and happy new year. 
👌❄️🎄.
